### PR TITLE
Add support for access-token secrets

### PR DESCRIPTION
**Pull request by mmaitre314**
- Implement #20 
- Add a new ACCESS_TOKEN secret provider
- Add test
- Include build instructions from the main duckdb repo in README.md

### CODE REVIEW

**Comment by samansmink** [comment]
Hey @mmaitre314 thanks for the PR, looks great! 

To fix the CI failure, could you add the `     ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true` env variable to the functional test CI jobs (like here https://github.com/duckdb/extension-ci-tools/blob/ebf18ed49b11e656adc20d721bf7dac2de15d439/.github/workflows/_extension_distribution.yml#L155) 
Our Linux CI is a little broken at the moment and while we refactor a few things we need to have this workaround.

**Comment by mmaitre314** [comment]
I added `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION` in a couple of places but I am not very confident in where I added that... If I understand correctly, patch [azure_http_state.patch](https://github.com/duckdb/duckdb/blob/1df7e09db158de84a87f02bc25d2c55b285f1d5a/.github/patches/extensions/azure/azure_http_state.patch) is not getting applied and the code tries to include `duckdb/common/http_state.hpp` which does not exist anymore.

**Comment by samansmink** [comment]
Ah I see, sorry I missed that Azures CI is running against DuckDB's main branch. Normally we have CI target latest stable and let duckdb/duckdb CI take care of catching changes breaking compatiblity.

I've applied the patch to your branch, this should fix ci here. Then we can bump azure's version in duckdb/duckdb ci and remove the patch.

**Comment by mmaitre314** [comment]
The formatting of HTTP stats changed a bit so I updated the Regex in the test to match.

Before: `ss << "││            HTTP Stats:            ││\n";`

Now: `ss << "││" + QueryProfiler::DrawPadded("Azure HTTP Stats", TOTAL_BOX_WIDTH - 4) + "││\n";`

**Review by samansmink — APPROVED** [review]

**Comment by samansmink** [comment]
thanks @mmaitre314!

**Comment by mmaitre314** [comment]
Looking into updating docs as next step, should I wait until a new version of DuckDB is released?

**Comment by Lyndon1994** [comment]
Hi @mmaitre314 
Please consider this scenario:

00:00, set access token in secret (assume One hour valid)
00:54, run a sql, with current token （token1)
00:55, refresh token to token2
01:01, token1 expired, the sql will be failed.

Will the sql execution detect the token expiration or re-fetch the token?

**Comment by mmaitre314** [comment]
@Lyndon1994 -- this does not automatically handle token refresh and the caller would need to ensure the token is valid for long enough.

**Comment by mmaitre314** [comment]
Not that I am aware of. This is an advanced scenario and I am not sure simplifying further would be worth the work (track token lifetime, add a callback to get a new access token from the caller, etc.). Other forms of secrets are more user friendly in that respect.

**Comment by Lyndon1994** [comment]
We got this issue in the Fabric Notebook, because we can only use access token to access OneLake.

**Comment by Lyndon1994** [comment]
Is it easy to read system environment variable to get access token?

**Comment by mmaitre314** [comment]
In Fabric Notebooks I believe `notebookutils.credentials.getToken('storage')` [[doc](https://learn.microsoft.com/en-us/fabric/data-engineering/notebook-utilities#get-token)] would be used to get access tokens, and likely not environment variables. I have limited experience with Fabric though so I'll ask around to see if there is some better guidance.

**Comment by Lyndon1994** [comment]
> Hi @mmaitre314 Please consider this scenario:
> 
> 00:00, set access token in secret (assume One hour valid) 00:54, run a sql, with current token （token1) 00:55, refresh token to token2 01:01, token1 expired, the sql will be failed.
> 
> Will the sql execution detect the token expiration or re-fetch the token?

I know this api. Yes, we use it. But just as I said before, if `notebookutils.credentials.getToken('storage')` has a 10-minute expiration, the duckdb job can only run for 10 minutes and it will not refresh the token. 
But if duckdb can read environment variables every time, we can have a background thread to refresh the token to environment variables. What do you think?

**Comment by Lyndon1994** [comment]
And I know that notebookutils.credentials.getToken('storage') can only ensure that it has at least 5 minutes expiration.

**Comment by mmaitre314** [comment]
There is a good chance that calling `CREATE SECRET` from a background thread with a refreshed access token will have the desired effect.

**Pull request merged**
